version: "3"
services:
    #Sonarr
    sonarr:
        image: cr.hotio.dev/hotio/sonarr
        container_name: sonarr
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
            - UMASK=000
        volumes:
            - ${DOCKER_PATH}/sonarr:/config
            - ${MEDIA_DISK}:/data
            - ${CACHE_SSD}/downloads:/downloads
        ports:
            - "8989:8989"
        restart: unless-stopped
    #Radarr
    radarr:
        image: cr.hotio.dev/hotio/radarr
        container_name: radarr
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
            - UMASK=000
        volumes:
            - ${DOCKER_PATH}/radarr:/config
            - ${DATA}:/data
            - ${CACHE_SSD}/downloads:/downloads
        ports:
            - "7878:7878"
        restart: unless-stopped
    #Nzbget
    nzbget:
        image: lscr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/nzbget:/config
            - ${CACHE_SSD}/downloads/usenet:/downloads/usenet
        ports:
            - 6789:6789
        restart: unless-stopped
    #Bazarr
    #  bazarr:
    #    image: lscr.io/linuxserver/bazarr
    #    container_name: bazarr
    #    environment:
    #      - PUID=${ID}
    #      - PGID=${ID}
    #      - TZ=${TZ}
    #      - UMASK_SET=000 #optional
    #    volumes:
    #      - ${DOCKER_PATH}/config/Bazarr:/config
    #      - ${MEDIA_DISK}/movies:/movies
    #      - ${MEDIA_DISK}/tvshows:/tv
    #    ports:
    #      - 6767:6767
    #    restart: unless-stopped
    ##Tautulli
    tautulli:
        image: lscr.io/linuxserver/tautulli
        container_name: tautulli
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/tautulli/config:/config
            - ${DOCKER_PATH}/plex/Library/Application Support/Plex Media Server/Logs:/logs
        ports:
            - 8181:8181
        restart: unless-stopped
    #plex
    plex:
        image: plexinc/pms-docker:plexpass
        container_name: plex
        environment:
            - PLEX_UID=${ID}
            - PLEX_GID=${ID}
            - TZ=${TZ}
            #- UMASK=000
            - PLEX_CLAIM=${PLEX_CLAIM}
            - ADVERTISE_IP=${PLEX_ADVERTISE}
            - ALLOWED_NETWORKS=${PLEX_ALLOWED}
        volumes:
            - ${DOCKER_PATH}/plex:/config
            - ${MEDIA_DISK}:/media
            - ${DATA}:/ssd
            - ${MEDIA_DISK}/transcode:/transcode
        ports:
            - "32400:32400/tcp"
            - "1900:1900/udp"
            - "3005:3005/tcp"
            - "5353:5353/udp"
            - "8324:8324/tcp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
            - "32469:32469/tcp"
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped
    #Wireguard
    #  wireguard:
    #    image: lscr.io/linuxserver/wireguard
    #    container_name: wireguard
    #    cap_add:
    #      - NET_ADMIN
    #      - SYS_MODULE
    #    environment:
    #      - PUID=${ID}
    #      - PGID=${ID}
    #      - TZ=${TZ}
    #      - SERVERURL=${MY_URL} #optional
    #      - SERVERPORT=${WIRE_PORT} #optional
    #      - PEERS=1 #optional
    #      - PEERDNS=auto #optional
    #      - INTERNAL_SUBNET=10.13.13.0 #optional
    #    volumes:
    #      - ${DOCKER_PATH}/wireguard/config:/config
    #   ports:
    #      - /lib/modules:/lib/modules
    #      - 51820:51820/udp
    #    sysctls:
    #      - net.ipv4.conf.all.src_valid_mark=1
    #    restart: unless-stopped
    #homer
    homer:
        image: b4bz/homer:latest
        container_name: homer
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/homer:/www/assets
        ports:
            - 2408:8080
        restart: unless-stopped
    #Omada
    Omada:
        container_name: omada-controller
        image: mbentley/omada-controller:latest
        volumes:
            - ${DOCKER_PATH}/omada/data:/opt/tplink/EAPController/data
            - ${DOCKER_PATH}/omada/work:/opt/tplink/EAPController/work
            - ${DOCKER_PATH}/omada/logs:/opt/tplink/EAPController/logs
        environment:
            - MANAGE_HTTP_PORT=8088
            - MANAGE_HTTPS_PORT=8043
            - PORTAL_HTTP_PORT=8088
            - PORTAL_HTTPS_PORT=8843
            - SHOW_SERVER_LOGS=true
            - SHOW_MONGODB_LOGS=false
            - SSL_CERT_NAME="tls.crt"
            - SSL_KEY_NAME="tls.key"
            - TZ=${TZ}
        ports:
            - 29814:29814
            - 8088:8088
            - 8043:8043
            # Optional old ports
            - 29810:29810/udp
            - 29811:29811
            - 29812:29812
            - 29813:29813
        restart: unless-stopped
    #prowlarr
    prowlarr:
        image: cr.hotio.dev/hotio/prowlarr:testing
        container_name: prowlarr
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
            - UMASK=000
        volumes:
            - ${DOCKER_PATH}/prowlarr:/config
        ports:
            - "9696:9696"
        restart: unless-stopped
    syncthing:
        image: lscr.io/linuxserver/syncthing
        container_name: syncthing
        #hostname: syncthing #optional
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/syncthing:/config
            - ${DOCKER_PATH}/compose:/data1
            - ${DOCKER_PATH}/homer:/data2
            #- /path/to/data2:/data2
        ports:
            - 8384:8384
            - 22000:22000/tcp
            - 22000:22000/udp
            - 21027:21027/udp
        restart: unless-stopped
    #watchtower
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        environment:
            - TZ=${TZ}
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_SCHEDULE=0 0 5 * * * #isso faria rodar todo dia 5 da manha
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
    #duplicati
#    duplicati:
#        image: lscr.io/linuxserver/duplicati
#        container_name: duplicati
#        environment:
#            - PUID=${ID}
#            - PGID=${ID}
#            - TZ=${TZ}
#            #- CLI_ARGS= #optional
#        volumes:
#            - ${DOCKER_PATH}/duplicati:/config
#            - ${BACKUP_PATH}:/backups
#            - ${DOCKER_PATH}:/source
#        ports:
#            - 8200:8200
#        restart: unless-stopped
    #overseerr
    overseerr:
        image: cr.hotio.dev/hotio/overseerr
        container_name: overseerr
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
            - UMASK=000
        volumes:
            - ${DOCKER_PATH}/overseerr:/config
        ports:
            - "5055:5055"
        restart: unless-stopped
    #transmission
    #  transmission:
    #    image: lscr.io/linuxserver/transmission
    #    container_name: transmission
    #    environment:
    #      - PUID=${ID}
    #      - PGID=${ID}
    #      - TZ=${TZ}
    #    volumes:
    #      - ${DOCKER_PATH}/transmission:/config
    #      - ${MEDIA_DISK}/torrent/downloads:/downloads
    #    ports:
    #      - 9091:9091
    #      - 51413:51413
    #      - 51413:51413/udp
    #    restart: unless-stopped
    #qbittorrent
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/qbittorrent:/config
            - ${MEDIA_DISK}/downloads:/downloads
        ports:
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
        restart: unless-stopped
    #sabnzbd
    sabnzbd:
        image: lscr.io/linuxserver/sabnzbd
        container_name: sabnzbd
        environment:
            - PUID=${ID}
            - PGID=${ID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_PATH}/sabnzbd:/config
            - ${DATA}/usenet:/data/usenet
            # - ${CACHE_SSD}/downloads:/downloads
        ports:
            - 8090:8080
        restart: unless-stopped
#    mc-server:
#        image: itzg/minecraft-bedrock-server
#        container_name: mc-server
#        environment:
#            - PUID=${ID}
#            - PGID=${ID}
#            - TZ=${TZ}
#            - SERVER-NAME=Dockorld
#            - EULA=TRUE
#            - GAMEMODE=survival
#            - DIFFICULTY=normal
#            - ALLOW-CHEATS=false
#            - MAX-PLAYERS=5
#            - ONLINE-MODE=false
#        volumes:
#            - ${DOCKER_PATH}/mc-server:/data
#        ports:
#            - "19132:19132/udp"
#        # To attach 
#        stdin_open: true
#        tty: true
#        restart: unless-stopped

#    minecraft:
#        image: itzg/minecraft-server
#        container_name: minecraft
#        environment:
#            PUID: ${ID}
#            PGID: ${ID}
#            level-name: "Dockorld"
#            VERSION: "1.18.2"
#            ONLINE_MODE: "FALSE"
#            TYPE: "FABRIC"
#            EULA: "TRUE"
#            GAMEMODE: "survival"
#            DIFFICULTY: "normal"
#            PVP: "FALSE"
#            MAX-PLAYERS: 5
#        volumes:
#            - "/volume/minecraft:/data"
#        ports:
#            - "25565:25565"
#            - "19132:19132/udp"
#        # To attach 
#        stdin_open: true
#        tty: true
#        restart: unless-stopped

    #bt-minecraft:
    #    image: itzg/minecraft-server
    #    container_name: bt-minecraft
    #    environment:
    #        PUID: ${ID}
    #        PGID: ${ID}
    #        TYPE: "FABRIC"
    #        VERSION: "1.18.2"
    #        GENERIC_PACK: "/packs/bfs.zip"
    #        FABRIC_LOADER_VERSION: "0.13.3"
    #        MEMORY: "5G"
    #        ONLINE_MODE: "FALSE"
    #        EULA: "TRUE"
    #        GAMEMODE: "survival"
    #        DIFFICULTY: "normal"
    #        PVP: "FALSE"
    #        MAX-PLAYERS: 5
    #    volumes:
    #        - "/volume/bt-minecraft:/data"
    #        - "/volume/packs:/packs"
    #    ports:
    #        - "25566:25565"
    #    # To attach 
    #    stdin_open: true
    #    tty: true
    #    restart: unless-stopped
        
    # enigma:
    #     #image: itzg/minecraft-server
    #     image: itzg/minecraft-server:java8-multiarch
    #     container_name: enigma
    #     environment:
    #         PUID: ${ID}
    #         PGID: ${ID}
    #         TYPE: "CURSEFORGE"
    #         #VERSION: "1.18.2"
    #         #GENERIC_PACK: "/packs/medieval.zip"
    #         CF_SERVER_MOD: "https://media.forgecdn.net/files/3768/774/Enigmatica6Server-1.2.1.zip"
    #         #FORGEVERSION: "36.2.30"
    #         #FABRIC_LOADER_VERSION: "0.13.3"
    #         #DEBUG: "TRUE"
    #         MEMORY: "5G"
    #         ONLINE_MODE: "FALSE"
    #         EULA: "TRUE"
    #         GAMEMODE: "survival"
    #         DIFFICULTY: "normal"
    #         PVP: "FALSE"
    #         MAX-PLAYERS: 5
    #     volumes:
    #         - "/volume/enigma:/data"
    #         - "/volume/packs:/packs"
    #     ports:
    #         - "25565:25565"
    #     # To attach 
    #     stdin_open: true
    #     tty: true
    #     restart: unless-stopped
        
    addarr:
        container_name: addarr
        image: waterboy1602/addarr
        restart: "no"
        network_mode: host
        volumes:
        - ${DOCKER_PATH}/addarr/config.yaml:/app/config.yaml:ro
        - ${DOCKER_PATH}/addarr/chatid.txt:/app/chatid.txt:rw
        - ${DOCKER_PATH}/addarr/admin.txt:/app/admin.txt:ro
        # - ${DOCKER_PATH}/addarr/allowlist.txt:/app/allowlist.txt:ro
        # - ${DOCKER_PATH}/addarr/logs:/app/logs:rw